// Rebalance Assistant backend:
// 1. Reads open ArbLivePosition records + latest ArbConfig.
// 2. Computes net delta drift (sum of net_delta_usd across all open positions).
// 3. If drift > max_net_delta_drift_pct * total_capital, generates one ArbTransfer
//    record per asset that carries non-zero delta. Each transfer is tagged
//    "Rebalance Buy" (to add exposure) or "Rebalance Sell" (to trim).
// 4. Returns the plan + created transfer IDs. Dry run supported.
//
// POST body: { dry_run?: boolean }
// Admin-only.

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    if (req.method !== 'POST') {
      return Response.json({ error: 'POST only' }, { status: 405 });
    }
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') {
      return Response.json({ error: 'Forbidden: admin only' }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const dryRun = body.dry_run === true;

    // Load config
    const configs = await base44.asServiceRole.entities.ArbConfig.list('-created_date', 1);
    const config = configs?.[0]?.data ? configs[0].data : configs?.[0];
    if (!config) return Response.json({ error: 'No ArbConfig found' }, { status: 400 });

    const totalCap = Number(config.total_capital || 0);
    const driftPct = Number(config.max_net_delta_drift_pct || 0.001);
    const driftCapUsd = totalCap * driftPct;

    // Load open positions
    const positions = await base44.asServiceRole.entities.ArbLivePosition.filter(
      { status: 'Open' }, '-snapshot_time', 100,
    );

    // Aggregate net delta per asset
    const byAsset = {};
    let totalDelta = 0;
    for (const p of positions) {
      const asset = p.asset || 'Other';
      const d = Number(p.net_delta_usd || 0);
      byAsset[asset] = (byAsset[asset] || 0) + d;
      totalDelta += d;
    }

    const withinThreshold = Math.abs(totalDelta) <= driftCapUsd;

    // Build rebalance plan — one leg per asset with non-trivial drift
    // Rule: if an asset's signed delta > $50 magnitude, create a transfer to flatten it.
    // Direction: positive delta (long imbalance) => Rebalance Sell. Negative => Rebalance Buy.
    const MIN_PER_ASSET_USD = 50;
    const plan = [];
    for (const [asset, delta] of Object.entries(byAsset)) {
      if (Math.abs(delta) < MIN_PER_ASSET_USD) continue;
      const type = delta > 0 ? 'Rebalance Sell' : 'Rebalance Buy';
      plan.push({
        asset,
        current_delta_usd: Number(delta.toFixed(2)),
        action: type,
        target_usd: Number(Math.abs(delta).toFixed(2)),
      });
    }

    // If dry run, return plan only
    if (dryRun || plan.length === 0) {
      return Response.json({
        ok: true,
        dry_run: dryRun,
        total_capital: totalCap,
        drift_cap_usd: driftCapUsd,
        total_delta_usd: Number(totalDelta.toFixed(2)),
        within_threshold: withinThreshold,
        by_asset: byAsset,
        plan,
        created: [],
        message: plan.length === 0 ? 'No rebalance needed — per-asset deltas below $50 threshold.' : 'Dry run — no transfers created.',
      });
    }

    // Create ArbTransfer records
    const today = new Date().toISOString().slice(0, 10);
    const tsSuffix = Date.now().toString(36);
    const created = [];
    for (let i = 0; i < plan.length; i++) {
      const leg = plan[i];
      const transfer = await base44.asServiceRole.entities.ArbTransfer.create({
        transfer_id: `REBAL-${tsSuffix}-${i + 1}`,
        transfer_date: today,
        type: leg.action,
        asset: ['BTC', 'ETH', 'SOL', 'USDC', 'USDT'].includes(leg.asset) ? leg.asset : 'Other',
        from_exchange: '',
        to_exchange: '',
        quantity: 0,
        usd_value: leg.target_usd,
        status: 'Planned',
        purpose: `Auto-rebalance: flatten $${leg.current_delta_usd} ${leg.asset} delta drift`,
        rebalance_impact_usd: -leg.current_delta_usd,
        notes: `Generated by Rebalance Assistant. Total book delta: $${totalDelta.toFixed(2)}, cap: $${driftCapUsd.toFixed(2)}.`,
      });
      created.push({ transfer_id: transfer.transfer_id, id: transfer.id, ...leg });
    }

    return Response.json({
      ok: true,
      dry_run: false,
      total_capital: totalCap,
      drift_cap_usd: driftCapUsd,
      total_delta_usd: Number(totalDelta.toFixed(2)),
      within_threshold: withinThreshold,
      by_asset: byAsset,
      plan,
      created,
      message: `Created ${created.length} rebalance transfer(s).`,
    });
  } catch (error) {
    console.error('generateRebalanceSignals error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});