import React, { useState } from 'react';
import { CheckSquare, Square } from 'lucide-react';

const CHECKLIST = [
  { id: 'account', label: 'Polymarket account created (verify legal status)' },
  { id: 'usdc', label: 'USDC deposited via Polygon network — not Ethereum mainnet' },
  { id: 'apikey', label: 'CLOB API key generated by signing from wallet' },
  { id: 'privatekey', label: 'Private key stored in env variable, never in code' },
  { id: 'installed', label: 'py-clob-client, websockets, all dependencies installed' },
  { id: 'paper', label: 'Bot running in paper trading mode' },
  { id: '200trades', label: '200+ simulated paper trades, win rate above 70%' },
  { id: 'killswitch', label: 'Kill switch configured at −40% total drawdown' },
  { id: 'dailyhalt', label: 'Daily loss halt at −20% configured and tested' },
  { id: 'telegram', label: 'Telegram alerts working for all trade events' },
  { id: 'maxpos', label: 'Maximum position size set to 8% of portfolio' },
  { id: 'liquidity', label: 'Only markets with >$50K liquidity in watchlist' },
  { id: 'firsttrade', label: 'First live trade placed at $1–5 USDC' },
  { id: 'monitoring', label: 'First week of live trades monitored trade-by-trade' },
];

export default function ChecklistPanel() {
  const [checked, setChecked] = useState(() => {
    try {
      return JSON.parse(localStorage.getItem('polybot_checklist') || '{}');
    } catch { return {}; }
  });

  const toggle = (id) => {
    const next = { ...checked, [id]: !checked[id] };
    setChecked(next);
    localStorage.setItem('polybot_checklist', JSON.stringify(next));
  };

  const done = Object.values(checked).filter(Boolean).length;

  return (
    <div className="rounded-xl border border-border bg-card p-5">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-foreground">Pre-Live Checklist</h3>
        <span className="text-xs font-mono text-muted-foreground">{done}/{CHECKLIST.length}</span>
      </div>
      <div className="h-1.5 rounded-full bg-secondary overflow-hidden mb-4">
        <div
          className="h-full rounded-full bg-gradient-to-r from-primary to-accent transition-all"
          style={{ width: `${(done / CHECKLIST.length) * 100}%` }}
        />
      </div>
      <div className="space-y-2.5">
        {CHECKLIST.map((item) => (
          <button
            key={item.id}
            onClick={() => toggle(item.id)}
            className="flex items-start gap-2.5 w-full text-left hover:opacity-80 transition-opacity"
          >
            {checked[item.id] ? (
              <CheckSquare className="w-4 h-4 text-accent shrink-0 mt-0.5" />
            ) : (
              <Square className="w-4 h-4 text-muted-foreground/40 shrink-0 mt-0.5" />
            )}
            <span className={`text-xs leading-relaxed ${checked[item.id] ? 'text-muted-foreground line-through' : 'text-foreground'}`}>
              {item.label}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}